version: '3.6'

services:
  api:
    container_name: team-finder-api
    build: ./api
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env

  ui:
    container_name: team-finder-ui
    build: ./ui
    restart: on-failure
    ports:
      - "3000:3000"
