name: '[API] Run tests'

# Automatically trigger for changes to ./api/* on push/PR
on:
  push:
    paths:
      - 'api/**'
    branches-ignore:
      - main

  pull_request:
    paths:
      - 'api/**'
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    # Set working directory for entire test
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew test