name: '[UI] Run tests'

# Automatically trigger for changes to ./ui/* on push/PR
on:
  push:
    paths:
      - 'ui/**'
    branches-ignore:
      - main

  pull_request:
    paths:
      - 'ui/**'
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    # Set working directory for entire test
    defaults:
      run:
        working-directory: ui

    strategy:
      matrix:
        node-version: [16.9]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          # This is passed into the `actions/cache` action under the hood,
          # and doesn't appear to be affected by `working-directory: ui`
          cache-dependency-path: 'ui/package-lock.json'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run typecheck
      - run: npm run lint:report